### ISSUE TITLE
Data Table "Temp"

### ISSUE THREAD

**Issue by violetteta8** [HydrodynamicsGroup/GitHubTests#3]
I noticed the data table is not writing like we'd like it. The thermocouple is taking a single reading every 10 seconds, the data table is also being written every 10 seconds. So, the Average, Max, and Min functions won't work (since you're only averaging a single value). What are some ways we can fix this? @cchabot @aconlen 

When you come up with some ways to do so, message here so we can discuss (and get a feel for GitHub) and then feel free to play with it and fix it in a new branch.

**Comment by aconlen** [comment]
I'll get started on this bug..

**Comment by violetteta8** [comment]
Looks like this is working properly now. Max, Mins, Averages, etc. are calculated off the 30 samples over a 5min period now.
