### ISSUE TITLE
Light on for Bracketed Temps

### ISSUE THREAD

**Issue by violetteta8** [HydrodynamicsGroup/GitHubTests#4]
I'd like you guys to come up with a means of turning the light on and off based on a bracketed temp. So, something like if it's warmer than 70 but cooler than 80 turn it on, otherwise turn it off. Or, install a second temp sensor (thermocouple or otherwise) and base the light off a difference between them or similar. Drop a note below here to describe the task you choose to tackle, create a new branch, and try to tackle it! Feel free to use the "Issues" tab to submit an issue, question, etc. and use the label/assignees to direct it to the right spot. Again, a big reason for these small exercises is so you can be thinking about functions and how the logger works, as well as getting familiar with the functionality of GitHub.

**Comment by aconlen** [comment]
Created a bracketed temp condition by adding an AND statement and creating a new MinTemp variable to add to the subroutine.

**Comment by violetteta8** [comment]
Looks like this is working properly
